version: '3'
services:

  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:latest
    networks:
      - HA_NETWORK
    volumes:
      # Mount for influxdb data directory
      - INFLUXDB-DATA:/var/lib/influxdb
      # Mount for influxdb configuration
      - INFLUXDB-CONFIG:/etc/influxdb/
  
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: telegraf:latest
    networks:
      - HA_NETWORK
    volumes:
      - TELEGRAF:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb

  kapacitor:
    image: kapacitor:latest
    networks:
      - HA_NETWORK
    volumes:
      - KAPACITOR-DATA:/var/lib/kapacitor
      - KAPACITOR-CONFIG:/etc/kapacitor
  
  chronograf:
    image: chronograf:latest
    networks:
      - HA_NETWORK
    volumes:
      - CHRONOGRAF-DATA:/var/lib/chronograf/
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
  
  grafana:
    image: grafana/grafana:latest
    networks:
      - HA_NETWORK
    volumes:
      - GRAFANA-CONFIG:/etc/grafana
      - GRAFANA-DATA:/var/lib/grafana
    links:
      - influxdb
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:dmarofer.mooo.info; PathPrefixStrip: /grafana"
        - "traefik.docker.network=HOMEASSISTANT_TRAEFIK_NETWORK"
        - "traefik.extern.frontend.protocol=http"
    environment:
     - GF_SERVER_ROOT_URL=http://dmarofer.mooo.info/grafana
      
  mqtt:
    container_name: MQTT
    restart: unless-stopped
    image: eclipse-mosquitto
    networks:
      - HA_NETWORK
    volumes:
      - MOSQUITTO:/mosquitto
      - /etc/localtime:/etc/localtime:ro
 
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/raspberrypi3-homeassistant
    depends_on:
      - influxdb
      - traefik
      - mqtt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - HOMEASSISTANT:/config
      - /etc/localtime:/etc/localtime:ro
      - DIEGO:/DIEGO
    networks:
      - HA_NETWORK
    ports:
      - "8123:8123"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=HOMEASSISTANT_homeassistant.1"
        - "traefik.port=8123"
        - "traefik.frontend.rule=Host:dmarofer.mooo.info; PathPrefixStrip: /homeassistant"
        - "traefik.docker.network=HOMEASSISTANT_TRAEFIK_NETWORK"
                   
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - HA_NETWORK
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]
      
volumes:
  INFLUXDB-DATA:
  INFLUXDB-CONFIG:
  TELEGRAF:
  KAPACITOR-DATA:
  KAPACITOR-CONFIG:
  CHRONOGRAF-DATA:
  GRAFANA-CONFIG:
  GRAFANA-DATA:
  MOSQUITTO:
  HOMEASSISTANT:
  PROXY_DATA:
  DIEGO:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.106,nolock,soft,rw"
      device: ":/DIEGO"
      
networks:
  HA_NETWORK:
    driver: overlay